services:
  postgres:
    hostname: postgres_host
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgresDb:/var/lib/postgresql/data
volumes:
  postgresDb: